spring:
  config:
    import:
      - aws-secretsmanager:/secret/algashop/product-catalog/redis-password?prefix=catalog.secrets.
      - aws-parameterstore:/config/algashop/product-catalog?prefix=catalog.params
      - aws-parameterstore:/config/algashop/shared?prefix=shared.params
  cloud:
    aws:
      credentials:
        access-key: test
        secret-key: test
      region:
        static: us-east-1
      #      endpoint: http://localhost:4566
      endpoint: http://algashop-localstack:4566 # Don't need in production, is only for develop
      s3:
        enabled: true
        path-style-access-enabled: true  # Don't need in production, is only for develop
  cache:
    type: redis
  mongodb:
    uri: ${catalog.params.mongodb.uri}
#    uri: mongodb://localhost:27017,localhost:27018,localhost:27019/product_catalog?replicaSet=rs0
#    uri: mongodb://root:algashop@localhost:27017/product_catalog?authSource=admin
#    representation.uuid: standard
  data:
    host: ${catalog.params.redis.host}
    port: ${catalog.params.redis.port}
    password: ${catalog.secrets.redis-password}
    database: ${catalog.params.redis.database}
    timeout: ${catalog.params.redis.timeout}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${shared.params.auth-server-url}
#          issuer-uri: http://auth.algashop.local:8081
#          jwk-set-uri: http://127.0.0.1:8081/oauth2/jwks

logging:
  level:
    org.mongodb.driver.protocol.command: DEBUG
#    org.mongodb.driver.protocol.query: DEBUG
#    org.mongodb.driver.connection: DEBUG
    org.mongodb.driver.cluster: OFF

algashop:
  data-load:
    enabled: true
    auto-delete: true
  mapping:
#    image-storage-url: http://localhost:4566/algashop-product-image
#    image-storage-url: http://algashop-localstack:4566/algashop-product-image
    image-storage-url: ${catalog.params.storage.image-storage-url}
  storage:
    s3:
      bucket-name: ${catalog.params.storage.bucket-name}